### PR TITLE
Require usage of Tuple in TS

### PR DESCRIPTION
**Pull request by EskiMojo14**
fixes https://github.com/reduxjs/redux-toolkit/issues/3459

### CODE REVIEW

**Comment by jmcpeak** [comment]
Beta works just fine, but I can't get this new Tuple change working. Any docs or examples for how to configure the store with middleware examples?

**Comment by markerikson** [comment]
@jmcpeak : can you show what you're trying to accomplish?

We do have an example in the beta docs, here:

- https://deploy-preview-3089--redux-starter-kit-docs.netlify.app/api/configureStore#middleware

**Comment by jmcpeak** [comment]
> @jmcpeak : can you show what you're trying to accomplish?
> 
> We do have an example in the beta docs, here:
> 
>     * https://deploy-preview-3089--redux-starter-kit-docs.netlify.app/api/configureStore#middleware

Here's my store.ts:

```
import storage from 'reduxjs-toolkit-persist/lib/storage';
import { configureStore } from '@reduxjs/toolkit';
import {
  FLUSH,
  PAUSE,
  PERSIST,
  PURGE,
  REGISTER,
  REHYDRATE,
  persistReducer,
  persistStore,
} from 'reduxjs-toolkit-persist';
import { setupListeners } from '@reduxjs/toolkit/query';
import globalErrorMiddleware from '@/redux/middleware/global-error';
import { permissionsReducer, uiReducer } from '@/redux/features';
import { roster } from '@/redux/services/roster';
import { upload } from '@/redux/services/upload';
import { userRole } from '@/redux/services/userRole';

const middlewareOptions = {
  serializableCheck: {
    ignoredActions: [FLUSH, REHYDRATE, PAUSE, PERSIST, PURGE, REGISTER],
  },
};
const permissionsPersistConfig = {
  key: 'permissions',
  storage,
  version: 1,
  blacklist: ['splashScreenVisible'],
};

export const store = configureStore({
  devTools: process.env.NODE_ENV !== 'production',
  middleware: (getDefaultMiddleware) =>
    getDefaultMiddleware(middlewareOptions).concat([
      globalErrorMiddleware,
      roster.middleware,
      upload.middleware,
      userRole.middleware,
    ]),
  reducer: {
    [roster.reducerPath]: roster.reducer,
    [upload.reducerPath]: upload.reducer,
    [userRole.reducerPath]: userRole.reducer,
    permissions: persistReducer(
      permissionsPersistConfig,
      permissionsReducer
    ) as typeof permissionsReducer,
    ui: uiReducer,
  },
});

export const persistor = persistStore(store);

setupListeners(store.dispatch);

export type RootState = ReturnType<typeof store.getState>;
export type AppDispatch = typeof store.dispatch;
```

**Comment by markerikson** [comment]
That looks mostly reasonable. What actual problem are you having?

(FYI it might be easier to chat over in the `#redux` channel in the Reactiflux Discord: https://www.reactiflux.com )

**Pull request merged**
