### PR TITLE
[TINY FIX] Improve badge display in readme

### PR DESCRIPTION
**Pull request by aholachek**
## Before:

Screen Shot 2019-11-24 at 9 38 51 AM

## After:

Screen Shot 2019-11-24 at 9 43 43 AM

### CODE REVIEW

**Comment by markerikson** [comment]
Ah, that explains why it wasn't showing up.  Yeah, there's that bit of a dichotomy between the package name and the repo name, and that was causing me problems.

Thanks!

**Comment by markerikson** [comment]
OH WOW!  I didn't even look at who was filing this PR at first.

I just wanted to say that your talk at ReactConf was **AMAZING!!!**

I don't do any kind of animation work or design stuff myself, but your presentation was fantastic!  You packed a ton of practical info and examples into that talk, and it was fascinating to look at the examples.  

Out of curiosity, what are you doing with RTK?

**Comment by aholachek** [comment]
I’m glad you liked the talk! I am not using redux-starter-kit yet but I was reading the tutorials in preparation for possibly refactoring our app at work to use it. The documentation is extremely good. (I really appreciated the “Redux Styleguide” you recently published as well).
I know the trend right now is to move logic inside of React components with hooks, but I feel like for me, keeping view logic separate from application logic is important for keeping an app easy to reason about and easy to update as it grows. So I’m really glad that to see how redux-starter-kit reduces a lot of the cognitive load of using redux and hopefully makes it a more attractive option to use.

**Comment by markerikson** [comment]
You're welcome!  And yeah, please let me know if you've got any feedback on using RTK.

**Pull request merged**
