### PR TITLE
 fix: api.util.resetApiState should reset useQuery hooks

### PR DESCRIPTION
**Pull request by phryneas**
This should provide a fix for #1725.

@ayushsharma82 could you please try this? In a few minutes, the CodeSandbox bot should comment on this issue and one of the links there should lead to installation instructions for this build.

### CODE REVIEW

**Comment by ayushsharma82** [comment]
@phryneas Tried this fix with my app and I can confirm that hooks are getting reset by looking at the placeholder components.

I'll also generate a small example to confirm that all hooks are getting reset or not.

**Comment by ayushsharma82** [comment]
@phryneas  I've made this small [demo](https://codesandbox.io/s/reduxjs-redux-toolkit-forked-qu9n6?file=/package.json:265-273) to track this issue. It does reset all the hooks but data is never loaded again if the query is present during the dispatch of `resetApiState`. Let me know if this is an intended behaviour.

Demo uses c7d0efeb

**Comment by phryneas** [comment]
Hmm you're right, that is not really optimal behaviour. I'll have to look into that tomorrow, but that could be tricky.

**Comment by phryneas** [comment]
@ayushsharma82 I think this should do it, but I'll have to reread that tomorrow. Your test seems to pass now - can you experiment a bit more with that please?

**Comment by ayushsharma82** [comment]
Sure, I'll add some more steps to that demo.

**Comment by ayushsharma82** [comment]
Works! ( https://codesandbox.io/s/reduxjs-redux-toolkit-forked-qu9n6?file=/src/App.tsx ) Added a 'hide' button to simulate query being removed and added again before/after dispatching `resetApiState`.

**Comment by dreyks** [comment]
Is this statement in docs still relevant or should it be removed?
https://github.com/reduxjs/redux-toolkit/blob/4afef4af288d1352975175de2f6dce98ce3759e4/docs/rtk-query/api/created-api/api-slice-utils.mdx#L371

**Pull request merged**
