### PR TITLE
Adds the option of generating real TS enums instead of string unions

### PR DESCRIPTION
**Pull request by labmorales**
Added an option of generating real TS enums on [oazapfts](https://github.com/cellular//pull/308) and was hoping to add the feature here as well 😄. I think a lot of people may benefit from this optional behavior.

It seems like the oazapfts version has all the features included on the oazapfts patched version therefore I replaced it with the new one that has the generate enums feature.

Right now it's just a config option, but I can create a CLI option for it as well. To use it the config file should pass the useEnumType option like this:

```ts
import type { ConfigFile } from '@rtk-query/codegen-openapi';

const config: ConfigFile = {
  schemaFile: './fixtures/petstore.yaml',
  apiFile: './fixtures/emptyApi.ts',
  outputFile: './tmp/example.ts',
  useEnumType: true,
};

export default config;
```

This fixes this [issue](https://github.com/reduxjs/redux-toolkit/issues/1889).

### CODE REVIEW

**Comment by dutradotdev** [comment]
+1

**Comment by labmorales** [comment]
@phryneas any chance you can take a look at this? 🥺 🙏

**Comment by labmorales** [comment]
@markerikson any chance you can take a look at this?

**Comment by silte** [comment]
+1

**Comment by basswouters** [comment]
@phryneas, @markerikson  When is it possible to check and merge this PR. Would be really helpful to a lot of dev's using the generator.

**Comment by fjakop** [comment]
@labmorales thanks for this great PR, unfortunately it seems that it would not compile with the latest master. Would it be possible tha you make it work again?

**Comment by fjakop** [comment]
@labmorales thanks for merging. It seems that it is necessary to upgrade typescript version as well, since build & tests would fail otherwise.
The test snapshots need some tweaking too, since the generator does not use camel case anymore and handles line wrapping slightly different.
A proposal with succeeding tests and github workflows can be found here https://github.com/fjakop/redux-toolkit2/commit/9265a0f843ddf3edab9abcfa28a86340a60442e5
Maybe you can use the changes.

**Comment by pkri1122** [comment]
Just to pitch in here, it would be really valuable in a current project I'm working on to be able to iterate over enums coming from the back end. One source of truth… @labmorales You're work on this is appreciated.

**Comment by ianldgs** [comment]
FYI: I've deployed @fjakop's branch in our internal NPM registry and been using it. Working really well!

**Comment by labmorales** [comment]
Hey, @fjakop thanks for the work! Really appreciate it 😄 . It should work now.

We've been using this type generator for about 6 months now for several projects (https://www.npmjs.com/package/rtk-query-codegen-openapi-labmorales). Not sure if that's enough to remove the "Please note that `@rtk-query/codegen-openapi` only has been tested with TS versions 4.1 to 4.5..." warning, but I removed it anyway. 😬

**Comment by labmorales** [comment]
Dang, it. [Git Operations are down](https://www.githubstatus.com/). Will push when it's back again.

**Comment by labmorales** [comment]
@phryneas @markerikson any chance one of you can take a look at this?

**Comment by fjakop** [comment]
@phryneas @markerikson can we help to get this PR merged?

**Comment by juliengbt** [comment]
+1 Definitely need this!

**Comment by Valli-** [comment]
oazapfts needs to be updated to Version 4.7.3

**Comment by labmorales** [comment]
> oazapfts needs to be updated to Version 4.7.3

Is there a reason for that @Valli- ? The [master](https://github.com/reduxjs/redux-toolkit/blob/master/packages/rtk-query-codegen-openapi/package.json#L59C47-L59C47) branch still points to the old patched version of oazapfts and the current version as it is ^4.2.0 will pick up 4.7.3 when the lock file is generated/updated.

Also, why bother? It's been almost a year since I opened this PR. It's not likely that this will get merged. If anyone is interested in using this feature you can use this fork of mine https://www.npmjs.com/package/rtk-query-codegen-openapi-labmorales .

**Comment by phryneas** [comment]
@labmorales I do hope to get back to the codegen and get *all* of the PRs for it in eventually - it's unfortunately one of those situations where most other parts of RTK (and my real life) take precedence over it and I'm the only active maintainer that is familiar with the codegen part - and meanwhile the task is getting bigger and bigger :/

I sincerely want to apologize. I hope I'll get around to it soon.

**Comment by Rafaa17** [comment]
Any updates on this?

**Comment by GeorchW** [comment]
I just wanted to make a PR on my own to just bump the oazapfts version, but then stumbled upon this PR that does the same and a bit more, and [this one](https://github.com/reduxjs/redux-toolkit/pull/3434) that also does the same. The changes are pretty straightforward, yet they have been open for many months.

My personal itch was that after an update on the backend (FastAPI/Pydantic), the Spec contained `const` properties, which the codegen just translated to `any`. This has long been fixed in oazapfts upstream. 

In general, I fear that this package might slowly die if more API spec generators use unsupported features and this package never gets any updates. I understand that the resources of the maintainers are limited. I'd be happy to help, but it's hard to contribute if PRs aren't reviewed or merged. Is there some other way I can help? I really like this project, but right now I can't recommend it due to the maintenance situation.

**Comment by msio** [comment]
Will be the feature please merged ?

**Comment by georgiev-anton** [comment]
Hello. We also really need this ability to generate enums, how can we help?

**Comment by markerikson** [comment]
Just to give people a sense of what's up on our side:

- Lenz is the only maintainer who's spent real time writing all the codegen stuff.  He's currently busy working on Apollo as his day job and hasn't had much time for RTK work in the last few months
- I've never worked on the codegens, and all my spare time is focused on trying to get RTK 2.0 out the door
- Ben hasn't touched the codegens, and has been helping with 2.0 changes as needed
- Matt has done _some_ work on the codegens, and said recently he might have some time to look at making some updates and dealing with PRs, but not sure when that will be

I acknowledge that the codegen side has been very neglected over the past year, and I'm sorry about that.  Unfortunately we really are all doing this in our spare time, and it's a question of prioritization and available expertise.

Realistically, once we get RTK 2.0 out the door, we can try to turn our attention to the codegen issues and PRs and try to address things there.  Now that we've de-scoped how much work will go into 2.0, I'm hopeful that _might_ be _relatively_ soon (next couple months?).

I also see a couple of offers to help, and I appreciate that. The biggest issue there is that I'm probably the one most likely to be hitting merge on PRs, and _I_ don't have time or mental capacity to A) read through these PRs and discussions, B) understand the intent, C) meaningfully review and validate changes and decide that they're ready to merge.

In theory, if someone could put in the effort to basically do most of that work for me and write it up as an extensive comment here, that would increase the changes I could eyeball it and say "okay, sounds good", and merge this.  Like, summarize the original comment, any key points from the rest of the discussion, give me some screenshots or code snippets of before and after output, and whatever else would be relevant to offload the work from my own brain :)

**Comment by GeorchW** [comment]
> In theory, if someone could put in the effort to basically do most of that work for me and write it up as an extensive comment here, that would increase the changes I could eyeball it and say "okay, sounds good", and merge this. Like, summarize the original comment, any key points from the rest of the discussion, give me some screenshots or code snippets of before and after output, and whatever else would be relevant to offload the work from my own brain :)


Let's see if it helps :-) Here's a summary of the background of this MR:

## Motivation of the PR

Generally, openapi-codegen depends on [oazapfts](https://github.com/oazapfts/oazapfts) for most of the heavy lifting.

So, a year ago, someone wanted to implement a feature that required support in oazapfts (PR #2376, issue #2135). To avoid waiting for oazapfts to merge the PR, oazapfts was forked into https://github.com/rtk-incubator/oazapfts . I think at the time, oazapfts was not properly maintained, which makes this decision kinda sensible -- the [PR in question](https://github.com/oazapfts/oazapfts/pull/207) was open for more than eight months, from Feb 2022 to Nov 2022. The corresponding PR has long been merged, and oazapfts' maintainer Xiphe [has messaged msutkowski about this](https://github.com/oazapfts/oazapfts/issues/320) afterwards. By now, the original oazapfts project seems healthy and alive again. However, we're still on the old fork here.

So, in this MR, @labmorales wants to have yet another feature from upstream oazapfts to be usable in openapi-codegen: generating proper enums instead of string unions. E.g. generating something like this:

```ts
export enum MyEnum {
    myFirstValue = "my-first-value",
    mySecondValue = "my-second-value",
}
```

instead of this:

```ts
export type MyEnum = "my-first-value" | "my-second-value"
```

I think the [test case over in the oazapfts PR](https://github.com/oazapfts/oazapfts/pull/308/files#diff-b7f7a588c7bbc91d7c774ff03f0b857b2ae55c4a0192e3e45619506d3072a9f6R58-R88) also explains it well.

Now, you might say, that's not a very critical feature, why all the hiss? Well, because this MR doesn't just provide us with this one feature, but with all features that have since been merged into oazapfts, like newer typescript support, support for the OpenAPI `const` prop, and much more. In fact, the RTK fork of oazapfts is, as of writing, 264 commits behind upstream.

That's why there's not one, but three open PRs that want to switch to the upstream oazapfts again, all for slightly different reasons: #2854 (this one), #3430, #3434 -- and I almost opened a fourth one.

## The changes

First of all, oazapfts and typescript are bumped. This causes a couple of issues that are subsequently fixed:

- In `cli.ts`, there's a check for the typescript version, which warns if the wrong one is installed. It's been removed. This looks fine to me.
- All the `factory.createXXXDeclaration` functions that come from the TypeScript API now accept one parameter less (I think it was related to decorators or something, which got deprecated and subsequently removed). That parameter was set to `undefined` anyway, so it's unlikely to cause a change. All the changes in `codegen.ts` and some in `generate.ts` are just removing this one parameter, so this also looks fine.
- In `generate.ts`, there's also the actual enum thing that the PR is titled for. This just looks like its passing the `useEnumType` option into oazapfts and the resulting `enumAliases` back into the TS `factory.createExportDeclaration`. It also changes up a couple of regexes, but I think that they are equivalent. I don't agree with those changes, it doesn't seem like it's getting more readable through them, but I'd say thats a nitpick, not worth the back and forth.
- The rest is pretty straightforward, I think. I'm not sure about the tests, it seems like there's no actual test case for the new behavior. It could be considered not to be necessary, since the actual functionality is contained in oazapfts and tested there.

## The discussion

The discussion doesn't contain much of interest, fjakop and labmorales helped each other out to make this branch work, many people say "yes please".

If this gets merged, #3434 can be closed. #3430 needs to be rebased, but the changes should become much smaller/easier to review.

---

So, I hope this was not too much of a wall of text. I know that I can't magically make your day 30 hours long, but maybe this makes the work take a bit less of the 24h you have :-)

**Comment by markerikson** [comment]
**_Wonderful_!**  @GeorchW , genuinely, _thank you_ for taking the time to write that up!  That was a _fantastic_ recap.  That gave me larger context, explained why this matters, summarized the changes, and gave reasons why it should be merged.

Skimmed the changes very briefly and they line up with what you're saying.  I am sorta curious about the (lack of?) test setup, but this all seems plausible.

I'll go ahead and merge this, close #3434 , and see if I can actually publish updated versions of the codegen packages.  (I _haven't_ tried to publish those before - need to confirm I do have permissions, and then give it a shot.)

If you or anyone else can do similar writeups for other major / important PRs, that would also be a _huge_ assist and help me figure out what to do with them.  (And yes, @GeorchW , that maybe includes the "delayed tag invalidation" PR that is sitting in the `2.0` milestone.  It's on my list to look at, but all that logic is _really_ fiddly and I haven't had time to go wrap my head around that problem space yet.)

Also to set some additional expectations:

- I'm giving a conference talk in London next week. Got my slides mostly ready, which is good, but I will be generally occupied next week with the conf.
- I _am_ dealing with a lot of complications in personal life atm, and those are taking up a lot of headspace and emotional attention.  That _is_ going to limit some of the time I can put into RTK for a while.
- I _absolutely_ want to get RTK 2.0 out the door, but that also means that anything not already on the `2.0` milestone list or otherwise immediately obviously critical is probably going to get ignored because I don't have mental space for it...
- but _if_ folks can do similar writeups on what certain PRs do and why they should go in, that would pop them up on my radar when I see the notification + comment and give me the ability to just say "LGTM" and merge.

**Comment by markerikson** [comment]
Hmm. Our tests are now failing on `master`.

Looking at them, they _seem_ to be snapshot tests failing due to slightly different output:

image

I see some `camelCase` fields changing to `snake_case`, an extra TS type exported, slightly better comment output.  

I _thinK_ these are all improvements?  Guess we'll go with it :)

**Comment by markerikson** [comment]
Also turns out I don't actually have NPM publish rights to `@rtk-query` atm :)  Getting that addressed!

**Comment by juliengbt** [comment]
> Hmm. Our tests are now failing on `master`.
> 
> Looking at them, they _seem_ to be snapshot tests failing due to slightly different output:
> 
> image
> 
> I see some `camelCase` fields changing to `snake_case`, an extra TS type exported, slightly better comment output.
> 
> I _thinK_ these are all improvements? Guess we'll go with it :)


Regarding the `snake_case`, it might be a bug looking at the code.

```typescript
// src/generate.ts ; line 262

const isPureSnakeCase = /^[a-zA-Z][\\w]*$/.test(param.name);
```

`\\w`should be `\w`

**Comment by markerikson** [comment]
Ah, gotcha! Could you file a PR to fix that?

Looks like it'll be a few hours until msutkowski can give me publish rights, and I'm busy this evening and first half of tomorrow.  I will try to get the new version out tomorrow!

**Comment by smff** [comment]
Thanks so much, guys, you’re incredible! Will be waiting for an update 🙏

**Comment by phryneas** [comment]
Released in [v1.1.0](https://www.npmjs.com/package/@rtk-query/codegen-openapi/v/1.1.0)

**Pull request merged**
