### PR TITLE
chore: Switch 4.9.2-rc to 4.9.5 since 4.9.5 has been released in TypeScript

### PR DESCRIPTION
**Pull request by kahirokunn**
I'm ready for review. Thx. 🙏

### CODE REVIEW

**Comment by markerikson** [comment]
Can you also update this to include 5.0, 5.1, and 5.2? Thanks!

**Comment by kahirokunn** [comment]
5.1 and 5.2 did not pass the test. 😭

**Comment by EskiMojo14** [comment]
yep, known issue https://github.com/reduxjs/redux-toolkit/issues/3758

**Comment by kahirokunn** [comment]
Then when those patches are released, I will move forward with this PR. 💪

**Comment by markerikson** [comment]
Eh, we ought to copy over the current workaround in the `v2.0-integration` branch. I'm going to ahead and merge this (including broken 5.1/5.2 checks), and then deal with fixing them before the next release.  Thanks!

**Pull request merged**
