### PR TITLE
Add `codemods-cli` and rewrite "object reducer" codemods

### PR DESCRIPTION
**Pull request by markerikson**
Ref: 

- #2301
- #2592

This PR:

- Adds `codemods-cli` as a dep
  - Does a bunch of automated and manual deduping of our dependencies, because we had a whole bunch of various Babel versions getting installed
- Adds a new `rtk-codemods2` temp folder as a playground for working with `codemods-cli`
- Sets up the scaffolding for revised versions of the `createReducer / createSlice.extraReducers` codemods
- Manages to get those codemods running as actual TS code using `ts-node`
- Copy-pastes the original contributed versions of the codemods, and reworks them to both compile correctly as TS code, and handle many more forms of "a function as a field inside of an object"
- Replaces the original `rtk-codemods` folder with the temp folder's contents
- Sets this up to actually publish
- Publishes `@reduxjs/rtk-codemods`

~~This isn't ready yet - I need to try out the "publish as a package and run via `npx`" steps.  Also, I'll need to move this over and replace the original `rtk-codemods` folder (and try getting the generated GH action running).  But, I think it's on the right track.~~

For the record, the variations I could think of are:

- keys:
  - computed key, variable: `[todoAdded]`
  - computed key, expression: `[todoAdded.type + "stuff"]`
  - plain object key: `todoAdded`
- functions:
  - arrow function: `key: () => {}`
  - arrow function, implicit return: `key: () => thing`
  - object method: `key()`
  - function expression: `key: function() {}`

Tagging @chriskrycho , @nullvoxpopuli , and @rwjblue as an FYI - you gave me pointers to using `codemods-cli`, thank you!  I figured you'd be interested in the result, and also that I managed to get a working example of writing the transforms themselves as TS.  Also @martinerko who implemented the original attempt at the codemods, which formed the basis for this.

### CODE REVIEW

**Comment by markerikson** [comment]
One bit of behavior I'm unclear on: the transforms seem to be adding blank lines before each expression.  That includes before the `extraReducers` line.

This is hardly the worst problem in the world, and anyone who's running a codemod should really run Prettier on their code before committing :) But I'm not sure what the specific cause is.

**Comment by markerikson** [comment]
This appears to pretty much work now!

```
$ npx @reduxjs/rtk-codemods createReducerBuilder ./modified/**/*.{js,ts}
Need to install the following packages:
  @reduxjs/rtk-codemods
Ok to proceed? (y) y
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
Processing 2 files...
Spawning 2 workers...
Sending 1 files to free worker...
Sending 1 files to free worker...
[BABEL] Note: The code generator has deoptimised the styling of home\npm-cache\_npx\c7474bb40fa6e968\node_modules\lodash\lodash.js as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of home\npm-cache\_npx\c7474bb40fa6e968\node_modules\lodash\lodash.js as it exceeds the max of 500KB.
All done.
Results:
0 errors
0 unmodified
0 skipped
2 ok
Time elapsed: 7.288seconds
```

The Babel warnings are annoying.  It's due to it trying to compile the transform files, and recursing into `node_modules`.  `jscodeshift` has a `--no-babel` CLI arg to disable that behavior, but `codemod-cli` doesn't use or expose that.  Filed https://github.com/rwjblue/codemod-cli/issues/249 asking for that to be added.

**Comment by markerikson** [comment]
Tested this out by cloning a couple random repos like https://github.com/brimdata/brim and running `npx @reduxjs/rtk-codemods createSliceBuilder "./packages/**/*.{js,ts}"`.  It appears to work as expected!

Might still need a another tweak or two, but I think this is good enough to merge into the 1.9 branch and check that box off.

**Comment by chriskrycho** [comment]
This is awesome! I have been thinking about how to wire up codemod-cli with TS for a while, so it's neat to see some "prior art" out in the world. 🎉

**Comment by markerikson** [comment]
LOOK I JUST RANDOMLY MASH KEYS UNTIL THE RED ERROR MESSAGES STOP EXPLODING OKAY?

(in all seriousness: I take both my day job and my Redux "job" seriously, but I think a lot of folks would be surprised at how much stuff ends up being just "I hacked at this and now it seems to work, ship it!"  The `useIsomorphicLayoutEffect` hook is a good example of that - I swiped it for use in React-Redux from the middle of the giant React issue thread on "why is `useLayoutEffect` warning in SSR?", and I think that helped prompted the spread through the ecosystem under the assumption that "well the React-Redux folks have to know what they're doing, right?")

in this case:

- I've used `ts-node` before and knew that I could call `require("ts-node").register()`, so I slapped that in the obvious entry points
- copy-pasted the `jest.config.js`, although I coulda written it myself if I wanted to
- Dug through the `jscodeshift` repo to figure out how to alter the parser (although I guess that's more about parsing the actual app code)

**Pull request merged**
