### PR TITLE
Fix link to configureStore API

### PR DESCRIPTION
**Pull request by nickmccurdy**

### CODE REVIEW

**Comment by phryneas** [comment]
Whoops. Thanks :sweat_smile:

**Comment by nickmccurdy** [comment]
Thanks for merging. For some reason clicking the link hides the sidebar, but it stays open if I go to the API via the navbar. Do you know if there's an easy way to fix this or am I missing something in the link?

**Comment by phryneas** [comment]
Nope :/ I'm not happy with the collapsing sidebar in general due to ctrl+f & a11y reasons though.

**Comment by markerikson** [comment]
This PR is actually busted - the Markdown link needs to end in `.md`

**Comment by markerikson** [comment]
Just went ahead and edited it on master.

The sidebar disappearing seems to be a Docusaurus v2 bug:

https://github.com/facebook/docusaurus/issues/2190

The fact that the sidebar collapses categories by default is a separate question.

**Comment by phryneas** [comment]
Weird, I had tested the netlify preview o_O ah well ^^

**Comment by nickmccurdy** [comment]
@markerikson Thanks, it's not hiding any more for me

**Pull request merged**
