### PR TITLE
Add extra to BaseQueryApi

### LINKED ISSUE #1377: BaseQueryApi doesn't include extra (ThunkAPI)
The `BaseQueryApi` is missing the `extra` property from the ThunkAPI.
```
export interface BaseQueryApi {
  signal: AbortSignal
  dispatch: ThunkDispatch<any, any, any>
  getState: () => unknown
  extra: unknown // <--- to add
}
```

A possible temporal workaround for those who need it is: `const extra = dispatch((_, __, extra) => extra)`

### PR DESCRIPTION
**Pull request by ricksanchez**
Fixes #1377 

extra prop added to BaseQueryApi

### CODE REVIEW

**Comment by phryneas** [comment]
Looks good so far. Could you please also add a test that shows passing `extra` through from the gDM argument to the baseApi?

**Comment by ricksanchez** [comment]
Done, there was also style issues that were not detected by the build.

**Review by phryneas — APPROVED** [review]
Looks good, let's see the tests :)

**Review by msutkowski — APPROVED** [review]

**Comment by ricksanchez** [comment]
What else is required in order to merge?

**Comment by phryneas** [comment]
Me not forgetting to press the "merge" button ^^

Thanks for the PR!

**Pull request merged**
