### PR TITLE
fix mistake in docs "automated-refetching.mdx"

### PR DESCRIPTION
**Pull request by 3b7ameed**

### CODE REVIEW

**Comment by markerikson** [comment]
I _think_ this may be correct as-is, actually.

By using a `queryFn`, and having it return null, it looks like it has the net effect of simply invalidating some tags with no other effect.

**Comment by phryneas** [comment]
Yes, that is intended like this. It is a mutation that is not initiating a trip to the server, by using queryFn to bypass baseQuery. 

Am 3. Oktober 2021 01:36:20 MESZ schrieb Mark Erikson ***@***.***>:
>I _think_ this may be correct as-is, actually.
>
>By using a `queryFn`, and having it return null, it looks like it has
>the net effect of simply invalidating some tags with no other effect.

-- 
Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by 3b7ameed** [comment]
Ah sorry guys I didn't know that

**Comment by markerikson** [comment]
No worries, we appreciate the effort!

**Pull request closed without merging**
