### PR TITLE
[WIP] create JS codeblocks from TS code in the docs

### PR DESCRIPTION
**Pull request by phryneas**
This works fine locally, let's see what netlify says about it.

### CODE REVIEW

**Comment by phryneas** [comment]
In this context: considering that I'm switching the examples here to the builder notation so that they work both in JS and TS, I noticed that we wouldn't really need the ["Non-String Action Types" chapter](https://github.com/reduxjs/redux-toolkit/pull/707/files#diff-50d55c309eeed94e273a2789a7732eaaR106-R144) any more, since the following is actually possible with the builder notation (even though it would error out in TS because `createAction` only accepts strings as a type):

```js
import { createAction, createReducer } from "@reduxjs/toolkit";
const INCREMENT = Symbol("increment");
const increment = createAction<number>(INCREMENT);

const counterReducer = createReducer(0, (builder) => {
  builder.addCase(increment, (state, action) => state + action.payload);
});

console.log("here comes:");
console.log(counterReducer(1, increment(5)));
```

Generally: what do we do with the map notation here? Completely omit it? Add a chapter "historic: map notation"?

**Comment by markerikson** [comment]
Yeah, I'm fine with switching the docs to emphasize the builder syntax first.  But, we ought to document that the object format is still there as long as it's, y'know, actually there :)

**Comment by phryneas** [comment]
Realistically, that'll never go away as it is what the builder notation is using internally :D
Even the new prepare notation uses the old prepare notation at runtime :laughing:

**Comment by phryneas** [comment]
pushed a WIP.

It is now possible to add markdown "links" that are resolved to include specific sections of a docblock.

e.g.
```md
[examples,params](docblock://createReducer.ts?token=createReducer&overload=1)
```
where the sections are currently summary,remarks,overloadSummary,overloadRemarks,examples,params

**Comment by phryneas** [comment]
I think that is more than enough for one pull request, so I'm gonna stop here for now.

Everything in the API documentation should now exist as TypeScript & JavaScript example (where that makes sense, anyways) and `createSlice` & `createReducer` now prefer the builder callback notation over the map object notation.

Some docs already moved into docblocks, keeping stuff in sync and adding more documentation to vscode users.

Also https://github.com/reduxjs/redux-toolkit/pull/707/commits/7bf739b19f684381850b5b6b56d80843a58c05b6 sneakily made it in here.

I'm now gonna resolve the merge conflicts and then call it a day. Would be great if you could take a look @markerikson  :)

**Comment by markerikson** [comment]
I just tried pulling down the branch, ran `npm i` in both the root and the `website` folders, and started up Docusaurus, but got this error:

```
Failed to compile

../docs/api/createAsyncThunk.mdx
TypeScript error in code block in line 1 of D:\Projects\redux\redux-starter-kit\docs\api\createAsyncThunk.mdx/codeBlock_9/store.ts
Cannot find module 'react-redux' or its corresponding type declarations.

  0  import { configureStore } from '@reduxjs/toolkit';
  1  import { useDispatch } from 'react-redux';
  2  const store = configureStore({ reducer });
  3  export const useAppDispatch = () => useDispatch();
```

Do we need to have the React-Redux types installed here or something?  I don't see them in either package file.

**Comment by markerikson** [comment]
Actually, I'm getting a _bunch_ of compile failures:

```
TypeScript error in code block in line 5 of D:\Projects\redux\redux-starter-kit\docs\api\immutabilityMiddleware.mdx/codeBlock_2/store.ts
Cannot find module './exampleSlice' or its corresponding type declarations.

  0  import { configureStore, createImmutableStateInvariantMiddleware } from '@reduxjs/toolkit';
  1
  2  import exampleSliceReducer from './exampleSlice';
  3
  4  const immutableInvariantMiddleware = createImmutableStateInvariantMiddleware({
  5      ignoredPaths: ['ignoredPath', 'ignoredNested.one', 'ignoredNested.two']
  6  });
  7
  8  const store = configureStore({
  9      reducer: exampleSliceReducer,
 10      // Note that this will replace all default middleware

 @ ./.docusaurus/registry.js 1:5568-5638 1:5389-5517
 @ ./node_modules/@docusaurus/core/lib/client/exports/ComponentCreator.js
 @ ./.docusaurus/routes.js
 @ ./node_modules/@docusaurus/core/lib/client/clientEntry.js
 @ multi ./node_modules/react-dev-utils/webpackHotDevClient.js ./node_modules/@docusaurus/core/lib/client/clientEntry.js../docs/api/serializabilityMiddleware.mdx
Cannot find module 'immutable' or its corresponding type declarations.
 @ ./.docusaurus/registry.js 1:6144-6217 1:5954-6090
 @ ./node_modules/@docusaurus/core/lib/client/exports/ComponentCreator.js
 @ ./.docusaurus/routes.js
 @ ./node_modules/@docusaurus/core/lib/client/clientEntry.js
 @ multi ./node_modules/react-dev-utils/webpackHotDevClient.js ./node_modules/@docusaurus/core/lib/client/clientEntry.js
```

**Comment by phryneas** [comment]
@markerikson should now work fine with windows file paths :)

**Comment by markerikson** [comment]
This looks good enough.  Let's put it in!

**Pull request merged**
