### PR TITLE
types: export `GetThunkAPI` type

### PR DESCRIPTION
**Pull request by shrouxm**
This utility type is useful for creating custom wrappers around `createAsyncThunk`.

### CODE REVIEW

**Comment by paulschreiber** [comment]
@markerikson Are you able to approve/merge this?

**Comment by paulschreiber** [comment]
@aryaemami59 can you review/approve this?

**Comment by aryaemami59** [comment]
@paulschreiber I cannot as I'm not a collaberator on this project. The maintainers are busy at the moment, I'm sure they will get to it eventually so please be patient.

In the meantime, CodeSandbox has created an npm package you can use without a local patch, you can use that until this PR gets looked at.
Screenshot 2024-04-09 000056
Screenshot 2024-04-09 001134

**Comment by EskiMojo14** [comment]
thanks! not sure when we'll next put together a release, but in the meantime the CodeSandbox build should hopefully suffice.

**Pull request merged**
