### PR TITLE
Fix link to explanation about non-serializable vals

### PR DESCRIPTION
**Pull request by dominikdosoudil**
Former link redirected to 404

### CODE REVIEW

**Comment by phryneas** [comment]
That seems to be an error with out documentation build system currently - that link has been working for years and *should* be the right link.

**Comment by dominikdosoudil** [comment]
@phryneas oh, okay, in that case this PR should be probably closed, right?

**Comment by phryneas** [comment]
Yeah, probably. Thank you a lot for bringing this to our attention though!

**Comment by markerikson** [comment]
FYI this turned out to be a new Docusaurus _feature_ :)  After some debate we ended up going with the changed URLs.  There was another PR that made this same fix, and I just reopened and merged that one.  Thanks for the help!

**Pull request closed without merging**
