### PR TITLE
support default return schemas in openapi codegen

### PR DESCRIPTION
**Pull request by barp**
Accidently closed PR, reopening it here.

### CODE REVIEW

**Comment by barp** [comment]
Can someone look at this?

**Comment by barp** [comment]
@phryneas Hi, you looked at this before can you continue the review?

**Comment by barp** [comment]
@EskiMojo14 you also looked at this, can you continue the review?

**Comment by iliapnmrv** [comment]
I also need this feature, it would be great if someone release it

**Comment by sqkrv** [comment]
bump for this feature to be implemented

**Comment by barp** [comment]
Bumping again to try and get some attention...

**Comment by phryneas** [comment]
It will take as long as it will take.

We all work on this voluntarily, and none of us uses the codegen, or anything using OpenAPI at all. 
Every few months, someone will sit down, go through the OpenAPI PR, tries to understand what features they are for, if they make sense and if they might be breaking the experience for other users, and gets to merging (if applicable).

Honestly, it's not really a "fun" activity, it's one we do because we don't want to leave people hanging. Regular pings don't make it a more attractive task, though.

In the meantime, CodeSandbox has created an npm package you can use without a local patch:
grafik
grafik

**Comment by barp** [comment]
Thanks for giving a details explanation on how to use the temporary packages, appreciate it.

**Comment by markerikson** [comment]
Should be live in https://github.com/reduxjs/redux-toolkit/releases/tag/%40rtk-query%2Fcodegen-openapi%402.0.0-alpha.0 ! Please try it out and let us know if it works.

**Comment by bayasdev** [comment]
Could we make this an opt-in feature? This change broke my project because our code generator relies on the default responses in the OpenAPI schema to define the error responses that could be returned by an endpoint. For example:

```yaml
/api/v2/users:
    get:
      operationId: ListUsers
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/usersList'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/errorResponse'
```

**Comment by markerikson** [comment]
@bayasdev yeah, makes sense. File a PR to make that configurable?

**Comment by bayasdev** [comment]
@markerikson PTAL https://github.com/reduxjs/redux-toolkit/pull/4591

**Pull request merged**
