### PR TITLE
add TS 5.5 to test matrix

### PR DESCRIPTION
**Pull request by EskiMojo14**

### CODE REVIEW

**Comment by aryaemami59** [comment]
https://github.com/reduxjs/redux-toolkit/blob/a152b9eec8c8caceb2d27cf40acad749f31d3eba/packages/toolkit/src/tests/configureStore.test-d.ts#L277-L278

```diff
- const counterReducer1: Reducer<number> = () => 0
- const counterReducer2: Reducer<number> = () => 0
+ const counterReducer1 = () => 0
+ const counterReducer2 = () => 0
```

This change seems to fix the issue related to TS 5.5.

**Comment by aryaemami59** [comment]
> it looks like the reverse mapping used by ReducersMapObject seems to have broken somehow

Yeah I'm not really sure why tbh, this also fixes it:

https://github.com/reduxjs/redux-toolkit/blob/a152b9eec8c8caceb2d27cf40acad749f31d3eba/packages/toolkit/src/tests/configureStore.test-d.ts#L277-L278

```diff
- const counterReducer1: Reducer<number> = () => 0
- const counterReducer2: Reducer<number> = () => 0
+ const counterReducer1: Reducer<number, UnknownAction> = () => 0
+ const counterReducer2: Reducer<number, UnknownAction> = () => 0
```

**Comment by EskiMojo14** [comment]
that makes no sense, UnknownAction is the default for that type parameter anyway 🤔 
`Reducer<number>` and `Reducer<number, UnknownAction>` should be equivalent.

wtf typescript? 😅

**Comment by aryaemami59** [comment]
> that makes no sense, UnknownAction is the default for that type parameter anyway 🤔
> `Reducer<number>` and `Reducer<number, UnknownAction>` should be equivalent.

Yeah I was thinking the exact same thing, I tried to dig to see what exactly causes the issue but I kind of gave up. I *think* it might be because when we explicitly pass in generic type parameters to `Reducer`, the type for `preloadedState` does not get inferred. It just becomes the default `State` because TS can't do partial inference for generic type parameters. I could be very well wrong though.

**Comment by EskiMojo14** [comment]
@aryaemami59 are you able to recreate it in the TS Playground? weirdly i can't seem to reproduce it there: https://tsplay.dev/N7kyEN

**Comment by Andarist** [comment]
TS playground repro: [link](https://www.typescriptlang.org/play/?ts=5.6.0-dev.20240709#code/JYWwDg9gTgLgBDAnmApnA3gKDnASigEwFcBjFKAGkwF84AzKCEOAIgAEpCiAPAKwGcA9DAgQANgGtgMFgG5MoSLAxUcJCADs6wAOZFOAZRGcqtBk1YcufISPFSZ8zFjWb+8TsTJQAXHi7eADwaRCAARuQAfHAAvHAAFACUsdEADPKuGu5w7tBocepauvooRnnx6HCepORw1Iny1JiYhdnqRBow5Phe5ACMfj01UMGhEVDRcUkpcOktbvDtnd0B5ABMg6sjIeFRsQnJMWlOrfC5nPuF2nqGxigV2FVbfi44cEtdUAPvEB2fQ94+qo3h91n5QVAAetgdRgWBOGIIABDAiEIxIrovR6uP79PypGGmBqYIA), the change bisects to https://github.com/microsoft/TypeScript/pull/57837

**Comment by Andarist** [comment]
Actual minimal repro: [TS playground](https://www.typescriptlang.org/play/?ts=5.6.0-dev.20240709#code/C4TwDgpgBAggxsAlgewHYB4AqUIA9gSoAmAzlCcAE6KoDmUAvOVTbQHyNQDeAUFFKEgAuKJgDcPAL4SaBSgDMAhnGgBVVAGtUyAO6p4SNDnyFSsBClTc+UANp4qigAqVkYEiIrU6AXREBXTW09CUkeQWgAJQgifxVKdABlTkVUEAAaWGMCYjIDS051LV19CzQOJgAKGwpFAhFkgB8oQKIIeRoY9JtlQ1QRGG6ASkYORIlw8CiYuIhKEgBZRTAAeQAjACsIBCSUtMyYbNM8sqsmIuDSvorrflsAaSgaKA0IEGR5KES-KGjY+KSDx8BzYoQmsjmShUUAAwmgOrR-JQIIlgMhkSswH0SLsmKkMlkHMdzH1CkESvlyrcoMj-nMRH9ZglEiCoM1GfFFst1lsdizYKCpDweG04AAbRTIqDyQKnKBweGIRHI1HoiC4qD4g5HXIkgrncl6SmoNjVfhubEiOGoBFIlFojFYyw4-kwNjDEQAN2QiCIE14-AVqAoNJm8QZYbm6FQ-gAtms5jdKiMGBwAAwSQNoEMUNUARk4QdtKodEEqXFDdMoUEkQzEUAA9A35chY7HCMAnp3kP5O2jyBBoMAABbQOauau0ZCanSKEBCnhBkMKwJyDlzPMRqvRuMJyhJlPpiZLzu55EAJkLiuV9rV5ZstKZIgD-Bbq43IhXqDXkcoee6-CSN0tYSEAA)

Consider me nerd-sniped. I will be digging into it more tomorrow.

**Comment by aryaemami59** [comment]
This looks very interesting.

**Comment by Andarist** [comment]
https://github.com/microsoft/TypeScript/pull/59232

**Comment by markerikson** [comment]
Where do we stand on this one?

**Comment by markerikson** [comment]
I think this is now a dupe of #4567 .

**Pull request closed without merging**
