### PR TITLE
Fix inference for reducers without actions specified

### PR DESCRIPTION
**Pull request by EskiMojo14**
fixes https://github.com/reduxjs/redux-toolkit/issues/3474

### CODE REVIEW

**Comment by EskiMojo14** [comment]
@einarq would you be able to try out the package built from this PR, see if it fixes your issue? 🙂

**Comment by einarq** [comment]
Sure, how do I reference it?

**Comment by EskiMojo14** [comment]
There are install instructions [here](https://ci.codesandbox.io/status/reduxjs/redux-toolkit/pr/3475/builds/381165) 😄

**Comment by einarq** [comment]
Ok. It solves the issue, but it introduces another issue (which might be
fine?).

I now get a TS error if I use create.reducer, but I don't supply any types
on the action.

[image: image.png]

**Comment by EskiMojo14** [comment]
hmm, that image doesn't seem to display on github. Could you post a snippet, or adjust the codesandbox with an example?

**Comment by einarq** [comment]
Didnt work when coming in via an email I guess, trying again.

image


Weird thing is that I'm unable to repro this on the sandbox

**Comment by einarq** [comment]
Got it now

https://codesandbox.io/s/slice-selector-circular-type-forked-exzu6c?file=/src/counterSlice.ts

**Comment by EskiMojo14** [comment]
ahh, I see - I'm tempted to say this is a good thing though, if you want a payload other than void you should provide it.

either by using the usual `PayloadAction<Payload>` or by doing `create.reducer<Payload>(`

**Comment by EskiMojo14** [comment]
in the meantime if you want the previous behaviour of using `any` you can always do something like 
```ts
export type TODOFIXME = any;

create.reducer<TODOFIXME>((state, { payload: { orderDir } }) => {})
```

**Comment by einarq** [comment]
We’ll just fix them as we go, but thanks!On 25 May 2023, at 12:22, Ben Durrant ***@***.***> wrote:﻿
in the meantime if you want the previous behaviour of using any you can always do something like
export type TODOFIXME = any;

create.reducer<TODOFIXME>((state, { payload: { orderDir } }) => {})

**Pull request merged**
