### PR TITLE
Fixed non working example in createEntityAdapter

### PR DESCRIPTION
**Pull request by danielepolencic**
You could not copy paste and run the code as there were missing interfaces.

### CODE REVIEW

**Comment by markerikson** [comment]
The snippets aren't formatted correctly. If you can reformat them, I'll merge this.

**Comment by danielepolencic** [comment]
Amended.

**Comment by markerikson** [comment]
Weird, Travis is complaining about some lint issue in `createAsyncThunk`?  Not an issue here.

**Comment by markerikson** [comment]
Thanks!

**Pull request merged**
