### PR TITLE
rtk-query-codegen-openapi: If tags are specified, they are now mapped to providesTags or invalidatesTags.

### PR DESCRIPTION
**Pull request by kahirokunn**
I'm already ready for a review.

### CODE REVIEW

**Comment by kahirokunn** [comment]
@msutkowski @phryneas 
I need your help 😭 
Locally, `netlify-build` succeeds, but CI doesn't pass.

**Comment by phryneas** [comment]
@kahirokunn you can ignore the website build as long as the CI build passes. Website is often a caching issue. But make sure the CodeSandbox build succeeds.

**Comment by kahirokunn** [comment]
@phryneas
I accomplished what I was told.
I think I've accomplished all the necessary requirements.
I'm eagerly awaiting this feature!

**Comment by phryneas** [comment]
Yup, sorry, I've got really time only every other friday. Which coincidentally is today - I'll try to get through some open PRs today.

**Comment by kahirokunn** [comment]
Thank you.

**Review by phryneas — APPROVED** [review]
Keeping it unmerged right now so it doesn't already show up in the docs.
I'll merge this in as soon as I start preparing the new release.

**Comment by ximxim** [comment]
@kahirokunn thanks for this solution. I am waiting for this to be merged. I ran into a typescript error tho that I wanted to share with you for a sanity check.

I notice we are adding `addTagTypes` in `injectEndpoints` options. However,  `injectEndpoints` doesn't have that option, instead `enhancedEndpoints` does. Any thoughts on this?

image

**Comment by kahirokunn** [comment]
@ximxim 

I think it is possible to avoid this by modifying the code to do enhancementEndpoints when there is an addTagTypes like this.

```
const injectedRtkApi = api.enhanceEndpoints({ addTagTypes: ['Hoge', 'Fuga'] }).injectEndpoints({ })
```

**Comment by kahirokunn** [comment]
@ximxim Supported. How about now?

**Comment by ximxim** [comment]
Holy quickness batman 🤯 . Let me test it out and get back to you in a few.

**Comment by ximxim** [comment]
Yup, that did it. I haven't tested it functionally yet, typescript issue is gone at least. 🙏 

image

**Comment by kahirokunn** [comment]
That was good!
I hope to be invited as a maintainer someday!

**Comment by ximxim** [comment]
I finally got around to functionally testing these changes. 

I was expecting to see `api.provided` key to have my `network` tag in there but it's empty. I can see the data in `[api]/queries.[networkControllerGetAll(undefined)].data` has my network data.

image

## Injected Code

```javascript
import { baseApi as api } from "./baseApi";
export const addTagTypes = ["Network"] as const;
const injectedRtkApi = api
  .enhanceEndpoints({
    addTagTypes,
  })
  .injectEndpoints({
    endpoints: (build) => ({
      networkControllerGetAll: build.query<
        NetworkControllerGetAllApiResponse,
        NetworkControllerGetAllApiArg
      >({
        query: () => ({ url: `/network`, providesTags: ["Network"] }),
      }),
    }),
    overrideExisting: false,
  });
export { injectedRtkApi as injectedApi };
export const { useNetworkControllerGetAllQuery } = injectedRtkApi;
```

**Comment by ximxim** [comment]
Oh I figured out why that's happening. `providesTags` key was in the wrong place:

## Wrong:

```javascript
query: () => ({ url: `/network`, providesTags: ["Network"] }),
```

## Right:

```javascript
query: () => ({ url: `/network` }),
providesTags: ["Network"],
```

## Injected Code

```javascript
import { baseApi as api } from "./baseApi";
export const addTagTypes = ["Network"] as const;
const injectedRtkApi = api
  .enhanceEndpoints({
    addTagTypes,
  })
  .injectEndpoints({
    endpoints: (build) => ({
      networkControllerGetAll: build.query<
        NetworkControllerGetAllApiResponse,
        NetworkControllerGetAllApiArg
      >({
        query: () => ({ url: `/network` }),
        providesTags: ["Network"],
      }),
    }),
    overrideExisting: false,
  });
export { injectedRtkApi as injectedApi };
export const { useNetworkControllerGetAllQuery } = injectedRtkApi;
```

## Results

image

**Comment by kahirokunn** [comment]
@ximxim Thx! I fixed it!

**Comment by ximxim** [comment]
Perfect. Works like a charm. Just tested it 🙏

**Comment by kahirokunn** [comment]
When will this one be merged? 👀

**Review by msutkowski — APPROVED** [review]
LGTM. I'll ping @phryneas tomorrow and see when we can time a release. If possible, I'd like to get a release of my patched versions of oazapfts and that PR in as well.

**Comment by phryneas** [comment]
@kahirokunn I was kinda waiting for the next release with this one since it contains a docs change that should be in sync with a release - and for that release I was waiting for that patched oazapfts version.

So now... pease really get that out quick @msutkowski  :)

**Comment by kahirokunn** [comment]
@msutkowski Now that the patched oazapfts version has been merged, there is nothing more to block this. Isn't that right?👀

**Comment by Nautman** [comment]
This feature seems really useful!

I was wondering if you think there will be a neat way to invalideTags from another file/api? @kahirokunn

For example, I have lots of `user/...` API calls, but they all rely on which level of authentication the user has. Therefore, when the API calls `auth/revoke` I would like it to invalidate all (or some) user calls.

**Comment by kahirokunn** [comment]
@Nautman Is this document what you want to know?
https://redux-toolkit.js.org/rtk-query/api/created-api/api-slice-utils#example-4

**Pull request merged**
