### PR TITLE
Support RegExp in ignoredPaths/ignoredActionPaths

### PR DESCRIPTION
**Pull request by indutny**
Fix: #2553

### CODE REVIEW

**Comment by indutny** [comment]
Hah! Sorry, looks like I messed up in the initial version of the Pull Request. Should be fixed now.

**Comment by markerikson** [comment]
Hey! I'm trying to update this PR by rebasing it and then adding RegExp support to the immutability middleware as well. I got that working locally, but for some reason I can't force-push to update the branch in your repo. I'm going to close this PR and open a new one. Thanks for getting this working!

**Comment by indutny** [comment]
No worries! Happy to see it merged!

**Comment by markerikson** [comment]
btw turns out I was being stupid :)  I'd copied an HTTP URL to your repo and set that as the remote, when it needed to be an SSH URL. _That's_ why I was getting a 403 error :)

**Comment by indutny** [comment]
Haha, I still don't know how people use HTTP urls for git, so I'd definitely run into the same.

**Comment by markerikson** [comment]
In my case, I had copied the branch URL from the top of this page and deleted the `/tree/feature/....` part to paste in as the remote URL.  Lesson learned!

**Pull request closed without merging**
