### PR TITLE
feat: Add the ability to type `StoreEnhancers`

### LINKED ISSUE #299: Error `enhancers` when init store with configureStore.
I have an error with enhancers,  it says: `Type 'StoreEnhancer<{}, {}>[]' is not assignable to type 'StoreEnhancer<{}, {}>[] | ConfigureEnhancersCallback | undefined'.` 

My code is written in Typescript:

My configureStore:
```
import { configureStore, getDefaultMiddleware } from '@reduxjs/toolkit';
import { routerMiddleware } from 'connected-react-router';
import { createInjectorsEnhancer, forceReducerReload } from 'redux-injectors';
import createSagaMiddleware from 'redux-saga';

import history from './routers/history';
import createReducer from './reducers';
import rootSaga from './sagas';

declare const module: any;

export default (initialState = {}) => {
    const reduxSagaMonitorOptions = {};
    const sagaMiddleware = createSagaMiddleware(reduxSagaMonitorOptions);
    const { run: runSaga } = sagaMiddleware;

    const middleware = [...getDefaultMiddleware(), sagaMiddleware, routerMiddleware(history)];

    const enhancers = [
        createInjectorsEnhancer({
            createReducer,
            runSaga,
        }),
    ];

    const store = configureStore({
        reducer: createReducer(),
        preloadedState: initialState,
        middleware,
        enhancers,
    });

    sagaMiddleware.run(rootSaga);

    if (module.hot && env !== 'production') {
        module.hot.accept('./reducers', () => {
            forceReducerReload(store);
        });
    }

    return store;
};
```

And reducers:
```
import { combineReducers } from '@reduxjs/toolkit';
import { connectRouter } from 'connected-react-router';

import reducerLoadingApp from './components/common/loading/loadingApp/reducer';

import history from './routers/history';

export default (injectedReducers = {}) =>
    combineReducers({
        router: connectRouter(history),
        loadingApp: reducerLoadingApp,
        ...injectedReducers,
    });
```
Plz tell me what am i doing wrong or give me a solution. Thank you.

### LINKED ISSUE #583: redux-offline typescript error in configureStore()
I am trying to configure my redux store with `redux-offline` and I get the following error:

```
Type '(createStore: StoreCreator) => <T extends { [key: string]: any; }>(reducer: (state: T, action: any) => T, preloadedState: T, enhancer: StoreEnhancer<T, {}>) => Store<...>' is not assignable to type 'StoreEnhancer<{}, {}>'.
  Type '<T extends { [key: string]: any; }>(reducer: (state: T, action: any) => T, preloadedState: T, enhancer: StoreEnhancer<T, {}>) => Store<T, AnyAction>' is not assignable to type 'StoreEnhancerStoreCreator<{}, {}>'.ts(2322)
```

This is my config:
```
import { offline } from '@redux-offline/redux-offline';

import createRootReducer from '../reducers';
import offlineConfig from './offlineConfig';

const history = createHashHistory();
const rootReducer = createRootReducer(history);
const router = routerMiddleware(history);
// const enhancer = applyMiddleware(thunk, router);
const middleware = [thunk, router];

function configureStore() {
  return configureStoreTK({
    reducer: rootReducer,
    middleware,
    enhancers: [offline(offlineConfig)]
  });
}

export default { configureStore, history };
```

I believe I followed the precedent set by the documentation for configuring `redux-offline`.

### LINKED ISSUE #699: Extra properties added to store by enhancers are not getting inferred by configureStore
I have a custom enhancer with the following signature:

```ts
export interface ExtraProperties<PS> {
  persistence: {
    getPersistentState: () => PS
    hydrate: (state: PS) => void
    flush: () => void
  }
}


 
const enhancer = (createStore: StoreEnhancerStoreCreator): StoreEnhancerStoreCreator<ExtraProperties<PS>> => {
  return <S = any, A extends Action = AnyAction>(
    reducer: Reducer<S, A>,
    preloadedState?: PreloadedState<S>
  ) => {
   ...
  }
}
```

However when I add this enhancer to `configureStore`, the type of the returned store doesn't change at all.

image

This is caused by the fact that configureStore has type parameters for the state, actions and middleware, but not for the enhancer.

image

### LINKED ISSUE #2241: Update `configureStore` to extract TS types from enhancers (including `dispatch` overrides)
### What version of React, ReactDOM/React Native, Redux, and React Redux are you using?

- React:  "^18.0.0"
- ReactDOM/React Native:  "^18.0.0"
- Redux: "^4.1.2"
- React Redux: "^8.0.0-rc.1"

### What is the current behavior?

the store:
```javascript
...
const sagaMiddleware = createSagaMiddleware(process.env.NODE_ENV !== "production" ? { sagaMonitor: sagaMonitor } : {});
const middlewareSeriesTwo = [reduxClipboardCopy, sagaMiddleware];
//
export const store = configureStore({
	reducer: rootReducer,
	middleware: (getDefaultMiddleware) => getDefaultMiddleware({
		serializableCheck: {
			ignoredActions: [FLUSH, REHYDRATE, PAUSE, PERSIST, PURGE, REGISTER, 'SERVICES2PDF']
		}
	}).concat(middlewareSeriesTwo),
	devTools: process.env.NODE_ENV !== "production",
	enhancers: (defaultEnhancers) => [reduxBatch, ...defaultEnhancers, reduxBatch]
});
```
on dispatching an array of actions, like:
```
dispatch([
someAction0(payload),
someAction1(payload) 
])
```
get type error :
```
Argument of type '({ payload: string; type: string; } | { payload: object; type: string; })[]' is not assignable to parameter of type 'AnyAction'.
  Property 'type' is missing in type '({ payload: string; type: string; } | { payload: object; type: string; })[]' but required in type 'AnyAction'.ts(2345)
[index.d.ts(19, 3): ]()'type' is declared here.
```
declaring
```
dispatch([
someAction0(payload),
someAction1(payload) 
] as any)
```
solves the problem but I think that is not what we want.

### What is the expected behavior?

To infer the array of actions  as in previous version.

### Which browser and OS are affected by this issue?

Server running on Debian /  Client  Windows, Chrome

### Did this work in previous versions of React Redux?

- [X] Yes

### PR DESCRIPTION
**Pull request by fostyfost**
fix #299
fix #583
fix #699
fix #2241

### CODE REVIEW

**Comment by fostyfost** [comment]
Should I fix tests that fail for reasons unrelated to my changes?

**Comment by markerikson** [comment]
Glancing at a couple of the errors:

```
Error: src/tests/configureStore.typetest.ts(13,15): error TS2305: Module '"../../node_modules/@reduxjs/toolkit/dist"' has no exported member 'ThunkMiddlewareFor'.
Error: src/tests/configureStore.typetest.ts(546,29): error TS2345: Argument of type '{ readonly type: "actionListenerMiddleware/add"; }' is not assignable to parameter of type 'Unsubscribe'.
  Type '{ readonly type: "actionListenerMiddleware/add"; }' provides no match for the signature '(): void'.
```

Those look like actual breakages to me.

**Comment by fostyfost** [comment]
@markerikson Can I make an analog of `MiddlewareArray` with `concat` and `prepend` methods in order to keep the enhancer types?

**Comment by fostyfost** [comment]
@markerikson could you please re-run the tests?

**Comment by fostyfost** [comment]
@markerikson can I get review results for my PR?

**Comment by markerikson** [comment]
Skimming through this, it seems promising. It's enough of a change that I think it needs to go into 1.9, though, not the next `1.8.x` release on `master`.

**Comment by markerikson** [comment]
OK, just had a chance to look through this.  Seems good! Rebased against latest `v1.9-integration` and force-pushed that up, and I'll merge this.

Unfortunately I have no specific ETA on when 1.9 will be ready.  It's been slow going so far, and there's a bunch of RTKQ issues and PRs outstanding.  But, you can try this out in the preview build from #2401 .

**Pull request merged**
