### PR TITLE
Implement codemods for createReducer and createSlice builder 

### PR DESCRIPTION
**Pull request by martinerko**
ref #2301

### CODE REVIEW

**Comment by phryneas** [comment]
Thanks! Could you please move this to a separate folder `packages/codemods`?

**Comment by markerikson** [comment]
@martinerko do you have time to move these files and update the PR, or should we handle it?

**Comment by martinerko** [comment]
> @martinerko do you have time to move these files and update the PR, or should we handle it?
Sorry I have been extremely busy last couple of weeks and I am afraid I will not have enough time untill end of this month. I am happy to look into it early September if that helps

**Comment by markerikson** [comment]
@martinerko no problem - I'll take care of updating this PR so we can get these published alongside 1.9 when it's ready (hopefully soon-ish!)

Thanks for putting this together!

**Comment by markerikson** [comment]
Looks like the commit was done directly on your fork's `master` branch, so I can't push my changes up.

Given that, I'm going to close this PR, cherry-pick the commit into a new branch myself, and push and merge that.

Thank you for putting these together!

**Comment by markerikson** [comment]
Ported to #2602 , moved them to a new `packages/rtk-codemods` folder and added a placeholder `package.json`.  Thanks!

**Pull request closed without merging**
