### PR TITLE
Add "Create a React Redux App" to quick start

### PR DESCRIPTION
**Pull request by nickmccurdy**
See reduxjs/redux#3726

### CODE REVIEW

**Comment by phryneas** [comment]
Could we add something like "a TS version is currently in the making"? 
I'd love to emphasize TS as being a first-class citizen as much as possible.

**Comment by nickmccurdy** [comment]
This is already live on the Redux docs and the TS version is almost done, so I figured it would be best to mention the JS version and then link it to the TS version once that's done

**Comment by phryneas** [comment]
That's fair :)

**Comment by nickmccurdy** [comment]
@markerikson @timdorr The site hasn't updated, is this an issue with Docusaurus' versioned docs (see discussion in https://github.com/reduxjs/react-redux/pull/1543#issuecomment-597119087)?

**Comment by markerikson** [comment]
Hmm.  No, we don't use versioning for RTK.  Also, I don't see a PR preview here.  Odd.

**Comment by markerikson** [comment]
Netlify says:

```
2:56:28 PM: Failing build: Failed to build site
2:56:28 PM: failed during stage 'building site': Deploy directory 'website/website/build' does not exist
2:56:28 PM: Finished processing build request in 1m5.805041136s
```

May be a path mismatch somewhere.

**Comment by markerikson** [comment]
Just fixed it with #422 , I think, although no idea why this was causing issues or seemed to work previously.

**Comment by nickmccurdy** [comment]
Thanks!

**Pull request merged**
