### PR TITLE
RTK Query: resolve type portability issues

### PR DESCRIPTION
**Pull request by markerikson**
Copy of #3569 by @eric-crowell  , rebased against `v2.0-integration`

### CODE REVIEW

**Comment by tdurnford** [comment]
@markerikson Will this fix be applied to v1.9 as well? If so, when will the next version be released?

**Comment by markerikson** [comment]
@tdurnford : no, these changes are just against v2.0 .

There's too many differences in build setup and configuration to try to backport them to 1.9.x at this point.

(Somewhat related: we'd _reallllly_ like people to try out the 2.0 betas and give us feedback on how they work.... :)  )

**Comment by tdurnford** [comment]
@markerikson I'm happy to test betas, but I can't take those to production 😢

Is there a GA target date for 2.0?

**Comment by tdurnford** [comment]
@markerikson Thank you for the update. I understand that is it important to be thorough when you do a major bump - you don't get very many opportunities and you don't want to be haunted by your choices.

I updated one of my side projects to use the new beta version. Overall, the migration was very smooth. I'll be sure to log any bugs or feature requests I come along. 

In the interim, I understand why you don't want to take the fix into 1.9.x, but do you have a potential mitigation? Our project is heavily dependent on  `@reduxjs/toolkit`, and the portability issue is causing major problems for us. 

Thank's again and I hope you have plenty time away from your keyboard to enjoy your family and golf while the weather is still nice - very important.

**Comment by markerikson** [comment]
@tdurnford : yeah, lemme clarify my stance here.

I've got enough on my plate that _I_ don't have time to try to backport this right now.  Also, there was a _lot_ of fiddly changes around types paths and references to `/dist/` that we had to change here in `v2.0-integration`.  Given that, I don't want to spend time myself backporting these.

However, if you or someone else can take the time to try backporting the changes to 1.9.x and see if they fix things there, sure, I'll happily accept a PR that improves things.

**Comment by tdurnford** [comment]
@ericanderson  I can spend some time looking into it. Can you point me to some of the _fiddly_ PRs that were necessary so I can get a general sense of the requirements?

**Comment by markerikson** [comment]
Yeah, some combination of #3605 , #3592 , and #3672 .

**Comment by tdurnford** [comment]
Hey, @markerikson, I have opened a draft PR #3728. Still verifying the fix actually works and solves our issue before publishing. Would you mind taking a look. Happy to make updates if needed.

**Comment by tdurnford** [comment]
@markerikson I wanted to check in to see if you've had a chance to take a look at my PR

**Comment by markerikson** [comment]
@tdurnford : nope, sorry. Haven't had time to do any Redux maintenance work the last couple weeks. I'll try to look at it when I have time, but got too many other things going on right now.

**Pull request merged**
