### PR TITLE
avoid relying on `this` in createSlice

### LINKED ISSUE #4070: selectSlice weird behavior
`
import { createSlice } from "@reduxjs/toolkit";
import type { PayloadAction } from "@reduxjs/toolkit";
import { useAppSelector } from "../store";

// Define a type for the slice state
interface UiState {
    popups: [];
}

// Define the initial state using that type
const initialState: UiState = {
    popups: [],
};

export const uiSlice = createSlice({
    name: "ui",
    initialState,
    reducers: {
        openPopup(state, action) {
            const { id, element } = action.payload;
            state.popups.push({ id, element });
        },
    },
    selectors: {
        selectUI: (ui) => ui,
    },
});

**export const useUI = () => useAppSelector((state) => uiSlice.selectSlice(state)); // WORK FINE**
**// export const useUI = () => useAppSelector(uiSlice.selectSlice); // NOT WORKS**

/** ERROR IN CONSOLE
 *  @reduxjs_toolkit.js?v=791f25be:2571 Uncaught TypeError: Cannot read properties of undefined (reading 'reducerPath')
    at selectSlice (@reduxjs_toolkit.js?v=791f25be:2571:37)
    at selectSlice (react-redux.js?v=791f25be:189:28)
    at memoizedSelector (react-redux.js?v=791f25be:46:38)
    at getSnapshotWithSelector (react-redux.js?v=791f25be:74:22)
    at mountSyncExternalStore (chunk-ZRJG7NCB.js?v=791f25be:12509:28)
    at Object.useSyncExternalStore (chunk-ZRJG7NCB.js?v=791f25be:13196:22)
    at useSyncExternalStore (chunk-2EXEP7CN.js?v=791f25be:1120:29)
    at useSyncExternalStoreWithSelector3 (react-redux.js?v=791f25be:81:23)
    at useSelector2 (react-redux.js?v=791f25be:243:27)
    at useUI (slice.ts:30:28)
 */

`

### PR DESCRIPTION
**Pull request by EskiMojo14**
fixes #4070 and #4054, and supercedes #4056

### CODE REVIEW

**Comment by aryaemami59** [comment]
wait does this mean now we could do:

```ts
const selectStatus = createSelector([selectSlice], counterSlice.getSelectors().selectStatus)
```

**Comment by phryneas** [comment]
@aryaemami59 I believe usually you would do either
```js
const selectStatus = counterSlice.selectors.selectStatus
// or
const selectStatus = counterSlice.getSelectors(selectSlice).selectStatus
```
although memoization of those would depend on the definition of `selectStatus`.

**Comment by EskiMojo14** [comment]
@aryaemami59 it means you could use `selectSlice` as an input selector (or pass it to `useSelector`) without needing to wrap it `(state) => slice.selectSlice(state)` or bind it `selectSlice.bind(slice)`, yes - though as Lenz said, for slice selectors you should just use the existing `.selectors`/`.getSelectors` mechanism.

**Review by markerikson — APPROVED** [review]
Seems reasonable at first glance

**Comment by aryaemami59** [comment]
@phryneas Sorry I should have given more context, you're right, I wouldn't necessarily want to memoize something like `selectStatus`, I talked with Ben a while ago about the ability to use `selectSlice` as an input selector inside `createSelector`, and I was just referring to that. 

@EskiMojo14 That's awesome, thanks!

**Pull request merged**
