### PR TITLE
Allow undefined return type for createAsyncThunk options

### LINKED ISSUE #594: Confirm createAsyncThunk's condition return type?
Hi all - encountering an issue with the return type of `condition` method. [The docs state](https://redux-toolkit.js.org/api/createAsyncThunk#canceling-before-execution) that you only need to return false if the condition is met. There isn't any info about also having to return something outside of that condition.

So I'm getting the following type error when only returning false:
`Type 'false | undefined' is not assignable to type 'boolean'.`

The solution is either return something outside of the condition...

```js
condition: (userId, { getState, extra }) => {
  if (someCondition) {
    return false;
  }
  return true;
}
```

Or update the typings to set the return type as `boolean | undefined` so you don't need to return something. 

I can contribute a fix to the types or add some clarification to the docs, just not sure what's the intended behavior 🙂  For now I'm returning true outside the condition.

### PR DESCRIPTION
**Pull request by melanieseltzer**
Closes #594

### CODE REVIEW

**Comment by markerikson** [comment]
Thanks! I'll try to get out another release in the next day or so.

**Comment by markerikson** [comment]
Okay, okay, so "next day or so" turned into "13 days".  Sorry!

But happy to say that https://github.com/reduxjs/redux-toolkit/releases/tag/v1.4.0 is out now :)

**Comment by melanieseltzer** [comment]
Ah awesome! 👏 Many thanks!

**Comment by markerikson** [comment]
Sure, and appreciate the detailed issue and PR!

**Pull request merged**
