### PR TITLE
Update compressed-size action

### PR DESCRIPTION
**Pull request by msutkowski**
Hoping this fixes the action as it fails often.

- Use @v2 instead of @v2-beta
- Remove fetch-depth as the default is 1

### CODE REVIEW

**Comment by phryneas** [comment]
:trophy:

**Comment by markerikson** [comment]
So one issue we've seen is that it doesn't show sizes for PRs from forks or something like that.

Supposedly https://github.com/kuldeepkeshwar/size-plugin-bot works better because it's a bot and not an action, or so the author told me.

Should we give that a shot?

**Comment by msutkowski** [comment]
@markerikson It looks like the action runs, but you have to click 'view details' to see the info instead of it posting a comment to the PR itself. 

In addition to what you linked, here are two alternatives by popularity:
1. ~~https://github.com/siddharthkp/bundlesize~~ - Being replaced by https://github.com/bundlewatch/bundlewatch#i-use-bundlesize-why-should-i-switch-to-bundlewatch ?
2. https://github.com/ai/size-limit

**Comment by markerikson** [comment]
Yeah, you can definitely click into the "Details" on PRs, but half the point is to get it as an auto-updated comment :)

Worth a shot to compare them.

**Pull request merged**
