### PR TITLE
restore size job

### PR DESCRIPTION
**Pull request by karankiri**

### CODE REVIEW

**Comment by markerikson** [comment]
.......

huh. Now I'm trying to remember why we (I?) apparently even renamed this in the first place :)

Oh. The job immediately fails with:

```

Run andresz1/size-limit-action@v1
/usr/local/bin/npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: rtk-monorepo@undefined
npm ERR! Found: eslint@7.32.0
npm ERR! node_modules/eslint
npm ERR!   dev eslint@"^7.25.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@"^8.0.0" from eslint-config-react-app@7.0.1
npm ERR! node_modules/eslint-config-react-app
npm ERR!   dev eslint-config-react-app@"^7.0.1" from the root project
```

That might have been why?  I think there might have been a conflict with our use of Yarn v3, and this action trying to install things via NPM somehow.

Could you look into that?

Thanks!

**Comment by karankiri** [comment]
Just read your conversation on this thread https://github.com/andresz1/size-limit-action/issues/77, I'm trying with the latest action version to see if it solves our problem, otherwise might have to use any other/custom action for this one.

**Comment by EskiMojo14** [comment]
no luck :(

**Comment by karankiri** [comment]
Yeah, Checked this issue, Seems like only option is to create fake yarn.lock file inside packages/toolkit folder as the action version with fix is not published yet https://github.com/andresz1/size-limit-action/pull/87, or to use other action for it.

**Comment by karankiri** [comment]
Just pushed a fake yarn.lock to see if it fixes the issue

**Comment by markerikson** [comment]
Assuming it does work: could we de-commit the fake `yarn.lock` file after that, and instead have the workflow do a `touch yarn.lock` prior to running the size action?  That would skip having the actual file as part of the repo

**Comment by markerikson** [comment]
Okay, latest error:

```

Run andresz1/size-limit-action@v1.7.0
/usr/local/bin/yarn install
➤ YN0000: ┌ Resolution step
Resolution step
➤ YN0000: └ Completed in 20s 508ms
➤ YN0000: ┌ Post-resolution validation
Post-resolution validation
  ➤ YN0028: │ The lockfile would have been modified by this install, which is explicitly forbidden.
➤ YN0000: └ Completed
➤ YN0000: Failed with errors in 20s 607ms
Error: The process '/usr/local/bin/yarn' failed with exit code 1
```

I... unfortunately mostly know how to work around this :(

So there's two options here, I think.

One is to delete the fake `yarn.lock` file _before_ we run Yarn to install deps.

The other is to swipe the hack I used over in the React-Redux repo for a CI task:

https://github.com/reduxjs/react-redux/blob/7a6e465d0f5d38a2a7827b45e593c7f9651542a7/.github/workflows/test.yml#L143

```yml
      - name: Install deps
        working-directory: ./redux-toolkit/examples/publish-ci/${{ matrix.example }}
        run: rm yarn.lock && YARN_ENABLE_IMMUTABLE_INSTALLS=false yarn install && YARN_ENABLE_IMMUTABLE_INSTALLS=false yarn add msw@latest
```

**Comment by karankiri** [comment]
Removed the yarn.lock file from commit, doing the yarn install in a separate step with `YARN_ENABLE_IMMUTABLE_INSTALLS=false`, let's see how it behaves

**Comment by markerikson** [comment]
Looks like the action is still running into the NPM issues:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: eslint-config-react-app@7.0.1
npm ERR! Found: eslint@7.28.0
npm ERR! node_modules/eslint
npm ERR!   dev eslint@"^7.25.0" from the root project
npm ERR!   peer eslint@">=7.0.0" from eslint-config-prettier@8.3.0
npm ERR!   node_modules/eslint-config-prettier
npm ERR!     dev eslint-config-prettier@"^8.3.0" from the root project
npm ERR!     dev eslint-config-prettier@"^8.3.0" from @reduxjs/toolkit@1.9.7
npm ERR!     packages/toolkit
npm ERR!       @reduxjs/toolkit@1.9.7
npm ERR!       node_modules/@reduxjs/toolkit
npm ERR!         workspace packages/toolkit from the root project
npm ERR!         20 more (@graphql-codegen/typescript-rtk-query, ...)
npm ERR!     1 more (@reduxjs/rtk-codemods)
npm ERR!   27 more (eslint-plugin-import, eslint-plugin-jest, ...)
```

**Comment by markerikson** [comment]
Superseded by later efforts, thanks!

**Pull request closed without merging**
