### PR TITLE
Revert "Use main reactiflux invite"

### PR DESCRIPTION
**Pull request by nickmccurdy**
Reverts reduxjs/redux-toolkit#768

Follow up on https://github.com/reduxjs/react-redux/pull/1673

### CODE REVIEW

**Comment by nickmccurdy** [comment]
CI is failing on the type test but I'm only modifying documentation

**Comment by phryneas** [comment]
Yeah, it's only Travis.

On the topic itself though: would this channel-specific invite work? As far as I remember, when signing up for the server, all channels are locked and you have to check a checkbox over in announcments or so to gain access. Landing in another channel might be counterproductive?

**Comment by nickmccurdy** [comment]
> Would this channel-specific invite work? As far as I remember, when signing up for the server, all channels are locked and you have to check a checkbox over in announcements or so to gain access. Landing in another channel might be counterproductive?

Yes. We've made our community channels public as we're now using [rule screening](https://support.discord.com/hc/en-us/articles/1500000466882-Rules-Screening-FAQ) instead of private channels with the Reaction Role bot

**Comment by phryneas** [comment]
Ah, I missed that! Then let's get it in :)

**Pull request merged**
