### PR TITLE
fix: docs spelling

### PR DESCRIPTION
**Pull request by gsfk**
Minor spelling fixes to docs: 
- correspondance -> correspondence
- fixed a few confusions between the possessive `its` and the contraction `it's`. This is a common mistake which also occurs in the code comments, ~but I've left those untouched~.

### CODE REVIEW

**Comment by EskiMojo14** [comment]
thanks! by the code comments, do you mean code in the docs or in our source code?

either way we'd welcome corrections - we just wouldn't cut a release for them

**Comment by gsfk** [comment]
I mean comments in source code, I found a few stray `it's` when I searched through them quickly.

> thanks! by the code comments, do you mean code in the docs or in our source code?
> 
> either way we'd welcome corrections - we just wouldn't cut a release for them

**Comment by EskiMojo14** [comment]
could you add corrections for those in this config? :)

**Comment by EskiMojo14** [comment]
thanks again!

**Pull request merged**
