### PR TITLE
Fix TS 4.7 compat

### PR DESCRIPTION
**Pull request by phryneas**
This should fix the 4.7 and ts-next builds.

### CODE REVIEW

**Comment by phryneas** [comment]
With node 16 now shipping an AbortController and IE being out of the game we could also consider removing the AbortController fallback in 2.0

**Comment by phryneas** [comment]
By now all TS errors outside of node_modules work, but I don't know why this is getting runtime errors now. Probably something with msw, I'll look into that another time and leave this open now

**Comment by phryneas** [comment]
openes an upstream issue at https://github.com/mswjs/msw/issues/1210

**Comment by phryneas** [comment]
referencing my upstream PR codesandbox build, this now seems to fix all the issues

**Comment by markerikson** [comment]
Superseded by #2373

**Pull request closed without merging**
