### PR TITLE
Use Record<EntityId, T> instead of Dictionary<T>

### PR DESCRIPTION
**Pull request by EskiMojo14**
as per #930, uses Record instead of Dictionary type, so user can choose whether `entities[id]` is possibly undefined via `noUncheckedIndexedAccess`

`selectById` uses a type helper I've published to match the user's setting.

### CODE REVIEW

**Comment by markerikson** [comment]
I know this is kinda picky, but I'd really rather not add another dependency just for this.  

Can we inline it?

**Comment by EskiMojo14** [comment]
yes, I can switch back to importing a TS file from src if you'd prefer.

**Comment by markerikson** [comment]
yes please :)

**Comment by Matt-Ord** [comment]
This conflicts with #2901 - I would you rather I remove the Dictionary type in that Pr instead?

**Comment by EskiMojo14** [comment]
if all goes to plan this should probably be in the next alpha, so if you're happy to fix any conflicts and include the changes in #3187 that would work - otherwise I'm happy to deal with any conflicts here should your MR go in first :)

cc: @markerikson

**Comment by Matt-Ord** [comment]
If possible it would be great if my pr could be merged first - it's been sitting around for a long time and I don't want to waste my time with yet another rebase

**Comment by Matt-Ord** [comment]
I think the use of 
```
Compute<UncheckedIndexedAccess<T>> 
```
is needlessly complex @markerikson would you merge it if I made the changes I suggested?

**Comment by EskiMojo14** [comment]
@Matt-Ord I'm confused what you're asking - #3187 is already merged?

**Comment by Matt-Ord** [comment]
> @Matt-Ord I'm confused what you're asking - #3187 is already merged?

Yeah but I'd suggested something that could have be improved in the review - if I did the improvement as another pr is that something that would be merged?

**Comment by Matt-Ord** [comment]
My point is it's not necessary if you replace it with Record<Id,T>[Id], which is a lot simpler

**Comment by EskiMojo14** [comment]
feel free to open a PR demonstrating that working - we'd be happy to have a less complex approach.

**Pull request merged**
