### PR TITLE
Use 'system' format option for ES browser builds

### PR DESCRIPTION
**Pull request by msutkowski**
Addresses #652.

This is 'hacky', but is the only way I can figure out how to get this to work with the current `tsdx` limitations.

Uses the unused `system` build format and just overrides the output for ES modules in the browser ~~with the same config Redux uses. Confirmed that the build does work by converting the Redux UMD example to use `configureStore`/`createSlice`.~~

Update: I spent some more time reviewing the `tsdx` source, and the default configuration for any build is basically identical to the config Redux used, so I just simplified things. A working repo of the build from this last commit can be seen here: https://codesandbox.io/s/rtk-as-esm-browser-module-1lvrs?file=/index.html

### CODE REVIEW

**Comment by phryneas** [comment]
Just gave it a test, seems to be working well. Dependencies also seem to be bundled, at least `immer` seems to do it's job.

Some HTML to test locally, for the lazy ^^

```html
<html>
    <head>
        <script type="module">
            import {configureStore, createReducer } from './redux-toolkit.esm.development.mjs';

            const reducer = createReducer([], {
                test1(state, action) {
                    state.push(1)
                },
                test2(state, action) {
                    state.push(2)
                }
            }, 
            [], 
            (state, action) => (console.log(action), state))

            const store = configureStore({
                reducer
            })

            const s1 = store.getState()
            store.dispatch({type: "test1"})
            const s2 = store.getState()
            store.dispatch({type: "test2"})
            const s3 = store.getState()

            console.log({s1,s2,s3})
        </script>
    </head>
    <body>
    </body>
</html>
```

**Comment by msutkowski** [comment]
If it's approved all around, I'll drop a quick reference to this build by the UMD docs

**Comment by markerikson** [comment]
Do we want to get this out with 1.5?

**Comment by phryneas** [comment]
Probably a good idea :)

**Pull request merged**
