### PR TITLE
Feature/add type parameter for id in create entity adapter

### LINKED ISSUE #2098: Add type parameter for Id in createEntityAdapter
Currently `createEntityAdapter` provides no type checking for the id of an entity

This prevents type checking when using the selectors, and means that the return type of functions such as `getAllIds` returns `EntityId[]` rather than a type specific to the entity.

Introducing an (optional) type parameter for Id will solve all of these propblems, and also allow for the newtype pattern to ensure types between different adapters do not get mixed up
```typescript
type MyIdType = string & { readonly __tag: unique symbol }
```

### PR DESCRIPTION
**Pull request by Matt-Ord**
Closes #2098
Re making the pr #2099 after was closed

### CODE REVIEW

**Comment by Matt-Ord** [comment]
What is the timeline for rtk 2.0? I'm happy to rebase/ re work this when it comes close to the next release.

**Comment by markerikson** [comment]
@Matt-Ord : we're actively working on RTK 2.0 now!  I've re-pointed this at our `v2.0-integration` branch. Please feel free to update this as needed!

**Comment by Matt-Ord** [comment]
Sorry for being slow to respond- I might have time to look at this at the weekend.
Do you think it would be better to have Id as the first type parameter (to mirror the type of Record) for types such as entity state? 
Also similarly for createEntityAdapter

**Comment by markerikson** [comment]
@Matt-Ord Hmm. No, the most important thing is the type of the data.  The ID thing still feels secondary to me.

**Comment by EskiMojo14** [comment]
closing in favour of #3187, now that's merged in :)

**Pull request closed without merging**
