### PR TITLE
Tutorials Section: Update code blocks with JS/TS toggle

### PR DESCRIPTION
**Pull request by PrinceRajRoy**
Kicking off #1203 

This PR updates the code snippets under Tutorials section to support JS/TS toggles

### CODE REVIEW

**Comment by PrinceRajRoy** [comment]
@phryneas The remark tool [removes `React` imports](https://deploy-preview-1230--redux-starter-kit-docs.netlify.app/tutorials/typescript#use-typed-hooks-in-components) in JS version if jsx is not used in the file. Is there a to skip that?

**Comment by phryneas** [comment]
Hmm. Not entirely sure to be honest. That could be a prettier thing maybe?

In this case - maybe just return a `<div>{/* rendering logic */}</div>`?

**Comment by markerikson** [comment]
I'm not sure it makes sense to have the code samples in the "TS Quick Start" page be compiled to plain JS, given that the entire point is to have them in TS :)

**Comment by PrinceRajRoy** [comment]
@markerikson I was thinking about it, then again the issue said All the snippets, so I thought that's included, anyways pushing the discarded changes 😅

**Comment by markerikson** [comment]
look you're supposed to read my mind and realize that when I said "all" I actually meant "all of them that make sense" even though I didn't specify that and wasn't even thinking about this case at the time :)

**Comment by markerikson** [comment]
looks good!

**Pull request merged**
