### PR TITLE
Adding correctly typed `` prepend`  and `` concat`  to the array…

### PR DESCRIPTION
**Pull request by phryneas**
This should solve #552 - opening as a draft PR because I want to re-review this tomorrow myself.

I streamed coding this live and it's available at https://www.youtube.com/watch?v=uQVJ6Aw3tho :smile: 

Also, this is based of #549, so once that is merged, this is probably more readable.

### CODE REVIEW

**Comment by phryneas** [comment]
Okay, moved the `MiddlewareArray` to `utils.ts`, exported it & added documentation. I believe this might be ready for review now.

**Comment by markerikson** [comment]
Tried merging #609, but that resulted in merge conflicts for this branch somehow. Let's just go with this one instead.

**Comment by elizabeth-dev** [comment]
Hi, maybe this isn't the best place to discuss this (sorry for that), but it's a bit awkward that the docs reflect the reference for versions that aren't published yet (I was trying to understand why the library typings didn't include the correct type definition for `middleware`, when I discovered that passing a function was a recent addition. Maybe a bit of Murphy's law that I went to check specifically that part of the docs just today).

Btw, thank you both for your work on this library.

**Comment by phryneas** [comment]
@elizabeth-dev Sorry for that - I'm just finishing the docs on #610 and we'll hopefully soon release the next version.

@markerikson This is actually a good point. Maybe we should deploy the docs from another branch? Might be finnicky though :/

**Comment by markerikson** [comment]
Hrm. Yeah, sorry about that.  

We do plan to release 1.4 in the next couple days or so, so hopefully the mismatch won't last long.

But yeah, for future work, let's try to do integration branches for new features + docs.

**Pull request merged**
