### PR TITLE
add baseQueryMeta to thunks, meta to lifecycle results

### PR DESCRIPTION
**Pull request by phryneas**
This contains #1083 and is a definite WIP, just want to see if it works for #1080

@TamasSzigeti could you give the CodeSandbox build of this a spin? Types are still missing, but `meta` is *on* there, so you might have to do an `any`-cast to get it out there atm. if working with TS

Install instructions at https://ci.codesandbox.io/status/reduxjs/redux-toolkit/pr/1084/

### CODE REVIEW

**Comment by TamasSzigeti** [comment]
Yes I'm using TypeScript and seems the parts relying on createAsyncThunk are having type errors now. Specifically in extraReducers where I'm using `builder.addCase(someThunk.fulfilled, (state, { payload }) => { … })`, it results in `payload` being typed as `unknown`.
I can try to spend more time on it tomorrow to understand it better.

**Comment by phryneas** [comment]
@TamasSzigeti I have added a test for that over at https://github.com/reduxjs/redux-toolkit/pull/1083/commits/64a8c64d6cc2ca035d93aa55e79b92cb3534341c#diff-a11e9f94b91b0761740b0b3daf0f10c2b45a1881e554e229914dc23d146826e1R104 but I cannot really reproduce that behaviour. Can you please create a reproduction?

**Comment by TamasSzigeti** [comment]
> @TamasSzigeti Can you please create a reproduction?

@phryneas I trimmed down my case, and it seems that the unknown payload comes about when I pass a second argument to the payloadCreator, whether I want to use `dispatch` or `getState`. When I leave that argument out, as the case in the tests, the return type is propagating just fine.

https://gist.github.com/TamasSzigeti/2ddade02d2e647d25d8810da04dba494

**Comment by phryneas** [comment]
Thank you @TamasSzigeti !
That one was actually super tricky to find & solve, but I think I got it. Can you try it again?

Thanks for the report :+1:  :smiley:

**Comment by TamasSzigeti** [comment]
> That one was actually super tricky to find & solve, but I think I got it. Can you try it again?

Nice, thank you! My case works perfectly having re-implemented it with `onCacheEntryAdded`. Meta is there, only the typing is missing.
Plus the serializability middleware is complaining about the meta field in the `api/executeQuery/fulfilled` action payload:
```
A non-serializable value was detected in an action, in the path: `meta.baseQueryMeta.request`
```

**Comment by phryneas** [comment]
Yup, the types will be the next step :) Thanks for validating!

**Comment by phryneas** [comment]
Aaand we have types.

**Comment by TamasSzigeti** [comment]
Awesomeness, and it works perfectly, same types as with onSuccess before. One thing that might worth adding to the docs is a note about when can the meta come through as undefined. I guess it has to do with an overridden queryFn?

Thanking muchly, this is becoming nice and clean, very pleasant to work with.

**Comment by phryneas** [comment]
@TamasSzigeti Those are always optional because I did not want to add multiple generic arguments here for something that is more of an "edge case" use.
Depending on your `baseQuery`, it might only return `meta` for successes, only for errors, or even none or different ones. I've put these into one "combined" generic argument to reduce complexity of the types (which already are insane anyways).

In the case of `fetchBaseQuery`, they should always be there with the maximum available information unless some unexpected error happened there and it actually crashed.

**Comment by TamasSzigeti** [comment]
@phryneas Thanks, my interpretation was correct then. My point is that this could be useful to be added in the docs.

**Pull request merged**
